Tarefa 13
ES-Group-2/psim-backend pull request #41
Opened 2021-04-25 21:28 UTC by gabryellesoares

2021-04-26 01:47 UTC, thiagoyeds requested changes
Ta indo no caminho, mas ainda tem umas coisinhas pra corrigir. Lembra de fazer o check up com [StandardJS e Jest](https://github.com/ES-Group-2/psim-backend/tree/pacote-3#antes-de-soliticar-merge-pr)

2021-04-26 01:47 UTC, thiagoyeds commented on package.json
> +    "https": "^1.0.0",
Isso é mesmo necessário?

2021-04-26 01:47 UTC, thiagoyeds commented on package.json
> +    "request": "^2.88.2",
Isso aqui também é necessário?

2021-04-26 01:47 UTC, thiagoyeds commented on src/api/controllers/QuestaoController.js
> +// const connection = require("../database/database");
Acho que não precisa desse comentário

2021-04-26 01:47 UTC, thiagoyeds commented on src/api/services/QuestaoService.js
> +    return questoes.sort(ordenaQuestoes).map((questao) => {
Antes de retornar aqui, provavelmente tem que fazer aquela modificação pra retornar o enunciado como lista de string e talvez pra alternativas também (não lembro se imagens precisa), o retorno tem que ser igual ao do [Swagger](https://app.swaggerhub.com/apis-docs/PSIM/PSIM/1.0.0#/questao/findAllQuestao)
```json
{
  "questoes": [
    {
      "id": 0,
      "ano": "string",
      "numero": "string",
      "enunciado": [
        "string"
      ],
      "alternativas": [
        "string"
      ],
      "imagens": [
        "string"
      ],
      "subarea": "string",
      "gabarito": 0
    }
  ]
}
```

2021-04-26 01:47 UTC, thiagoyeds commented on src/routes/QuestaoRouter.js
> +const http = require('https')
Isso aqui é necessário?

2021-04-26 20:10 UTC, thiagoyeds requested changes
Ainda falta fazer o check up do [StandardJS e Jest](https://github.com/ES-Group-2/psim-backend/tree/pacote-3#antes-de-soliticar-merge-pr)

2021-04-26 20:10 UTC, thiagoyeds commented on src/api/services/QuestaoService.js
> +        enunciado: questao.enunciados.map((enunciados) => {
Isso garante a ordem pelo índice? se o BD trouxer o índice 2 depois o 1 não vai ficar invertido?

2021-04-26 20:10 UTC, thiagoyeds commented on src/api/services/QuestaoService.js
> +        alternativas: questao.alternativas.map((alternativas) => {
Mesma coisa aqui? (Isso garante a ordem pelo índice? se o BD trouxer o índice 2 depois o 1 não vai ficar invertido?)

2021-04-27 17:47 UTC, thiagoyeds approved these changes
NICE DEMAIS!

2021-04-27 18:22 UTC, GustavoGCC commented
StandardJS: Nada encontrado
SonarJS: Finished analyzing /home/gustavo/psim-backend/psim-backend/src
                No issues found
Semgrep: ran 245 rules on 0 files: 0 findings

2021-04-27 18:42 UTC, merged