Adicionando a rota de GET de um simulado
ES-Group-2/psim-backend pull request #56
Opened 2021-05-04 12:39 UTC by Gabriel-de-Carvalho

![Captura de tela de 2021-05-04 09-36-34](https://user-images.githubusercontent.com/34272767/117004549-8d563b80-acbc-11eb-9ec6-580bd8de70a6.png)

2021-05-04 17:12 UTC, Gabriel-de-Carvalho commented
Print dos testes apos alterações.
![Captura de tela de 2021-05-04 14-08-12](https://user-images.githubusercontent.com/34272767/117042696-aeca1e00-ace2-11eb-98b6-a7fd944fc360.png)

2021-05-04 21:36 UTC, thiagoyeds requested changes
Ainda nao rodei os testes, mas por enquanto vejo esses detalhes pra arrumar

2021-05-04 21:36 UTC, thiagoyeds commented on src/api/services/SimuladoService.js
> +  return { status: 200, simulados: simuladosQuestaoCResposta }
Nao entendi, na API do Swagger não tem esse `simulados: {}` (https://app.swaggerhub.com/apis-docs/PSIM/PSIM/1.0.0#/simulado/findSimuladoById), deve-se seguir a API Swagger. Conversei com Gustavo, os testes mudaram isso

2021-05-04 21:36 UTC, thiagoyeds commented on src/routes/QuestaoRouter.js
> +QuestaoRoutes.post('/questoes', QuestaoController.store)
Aqui tem que voltar a comentar essa linha

2021-05-05 19:58 UTC, thiagoyeds approved these changes
Ta top! o/ hehe No caso do SimuladoPessoais.test.js so foi testado o caso do GET (PUT será no outro PR)
![AutenticacaoRouter test tarefa22](https://user-images.githubusercontent.com/15807921/117201417-0344ca80-adc3-11eb-8a5c-55f1c35f13f7.png)
![QuestoesRouter test tarefa22](https://user-images.githubusercontent.com/15807921/117201437-08097e80-adc3-11eb-8000-0ebaa18dc5c5.png)
![SimuladoRouter test tarefa22](https://user-images.githubusercontent.com/15807921/117201456-0b046f00-adc3-11eb-89fb-228b033d3569.png)
![SimuladosPessoais test tarefa22](https://user-images.githubusercontent.com/15807921/117201468-0d66c900-adc3-11eb-8c0a-41ae9b932477.png)

2021-05-05 20:30 UTC, GustavoGCC commented
Semgrep: ran 245 rules on 45 files: 0 findings
SonarJS: Finished analyzing /home/gustavo/psim-backend/psim-backend/src
No issues found
Standard: Nenhum resultado
Ferramentas aprovaram o PR

2021-05-05 20:40 UTC, merged